version: '3.9'

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: link-boss-api
    volumes:
      - .:/home/node/app
    ports:
      - '3333:3333'
    depends_on:
      - db

  db:
    build: .docker/postgres
    restart: always
    tty: true
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    env_file:
      - '.env'

  redis:
    image: 'redis:alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - '.docker/redisdata:/var/lib/redis/data'

  pgadmin:
    image: dpage/pgadmin4
    tty: true
    env_file:
      - '.env'
    ports:
      - '9000:80'
    depends_on:
      - db
